Lesson 2 home work
Keos99/java-reboot pull request #3
Opened 2023-10-26 22:31 UTC by Keos99

2023-10-28 17:20 UTC, rsmitt commented on module02/src/main/java/ru/sberbank/edu/FileHandler.java
> +            input = new BufferedReader(new java.io.FileReader(file));
у вас ресурс не закрывается. Оберните пожалуйста в try with resources

2023-10-28 17:22 UTC, rsmitt commented on module02/src/main/java/ru/sberbank/edu/DataStorageFileImpl.java
> +            writer.close();
если произойдет ошибка до close ресурс не закроется. Оберните в try with resource

2023-10-28 17:23 UTC, rsmitt requested changes
исправьте пожалуйста замечания

2023-10-29 15:22 UTC, Keos99 commented on module02/src/main/java/ru/sberbank/edu/FileHandler.java
> +            input = new BufferedReader(new java.io.FileReader(file));
В данном месте не целесообразно использовать try with resources. Т.к. после выполнения метода, а это просто чтение файла, мы получаем закрытый стрим. И соответственно не можем уже использовать данные. try with resources к данному ресурсу используется в методах статистики. Если указан неверный путь к файлу то объект Reader даже не создаётся. В данном случае соединение с ресурсом не будет установлено.

2023-10-29 15:28 UTC, Keos99 commented on module02/src/main/java/ru/sberbank/edu/DataStorageFileImpl.java
> +            writer.close();
исправил

2023-11-01 19:05 UTC, Keos99 commented
Проверьте пожалуйста.

2023-11-04 17:13 UTC, rsmitt commented on module02/src/main/java/ru/sberbank/edu/FileHandler.java
> +            input = new BufferedReader(new java.io.FileReader(file));
Кроме не найден файл, может еще много ошибок. Вы уверены что во всех кейфах ресурс не будет создан? Если ресурс зарывается, значит надо в случае ошибки попытаться закрыть. Ок, можно допустим в catch добавить проверку if input !=null input.close() + обернуть в try. Тогда 100% у вас не будет утечки. Код где не закрывается ресурс, вызывает сомнения в корректности

2023-11-04 17:24 UTC, rsmitt approved these changes

2023-11-06 01:20 UTC, Keos99 commented on module02/src/main/java/ru/sberbank/edu/FileHandler.java
> +            input = new BufferedReader(new java.io.FileReader(file));
Спасибо, да такой вариант тоже рассматривал.

2023-11-06 01:21 UTC, merged